DROP VIEW IF EXISTS STREAM_COUNT_BY_COUNTRY;

CREATE VIEW STREAM_COUNT_BY_COUNTRY(Country,StreamCount)
AS
SELECT Country, COUNT(StreamId)
  FROM CUSTOMER LEFT OUTER JOIN STREAM USING(CustomerId)
  GROUP BY Country;
