DROP VIEW IF EXISTS DEPARTMENT_STAFF;

CREATE VIEW DEPARTMENT_STAFF(DName,SName,Job)
AS
SELECT D.Name, S1.Name, S1.Job
FROM DEPARTMENT D  JOIN STAFF S1
WHERE (D.Manager= S1.StaffId OR D.Manager = S1.Supervisor)
