SELECT COUNTRY.Name, GENRE.Label, COUNT(StreamId)
FROM CUSTOMER JOIN COUNTRY ON(COUNTRY.Name=CUSTOMER.Country) JOIN REGION USING(RegionId)
            JOIN CUSTOMER ON(COUNTRY.Name=CUSTOMER.Country)
            JOIN STREAM USING(CustomerId)
            JOIN MOVIE USING(MovieID)
            JOIN MOVIE_GENRE USING(MovieID)
            JOIN GENRE USING(GenreId)
WHERE REGION.Name = 'Other Countries'
GROUP BY STREAM.StreamId
ORDER BY COUNTRY.Name, GENRE.Label;
