SELECT * FROM STREAM
WHERE Charge > 6
ORDER BY StreamDate DESC
LIMIT 20;


SELECT CUSTOMER.Country, COUNT(CustomerId) AS cnt
FROM CUSTOMER
WHERE CUSTOMER.Name LIKE '%y%'
GROUP BY CUSTOMER.Country
HAVING cnt >=3
ORDER BY cnt DESC,CUSTOMER.Country ASC;

DELETE FROM STREAM
WHERE STREAM.Charge<=7.5
      AND STREAM.MovieId IN(
        SELECT MOVIE.MovieId FROM MOVIE
        WHERE MOVIE.Title LIKE 'Star Wars%'
      );

SELECT CUSTOMER.Name, CUSTOMER.Country, CUSTOMER.City
FROM CUSTOMER JOIN COUNTRY ON (CUSTOMER.Country = COUNTRY.Name)
              JOIN REGION USING(RegionId)
      WHERE REGION.Name = 'Africa'
GROUP BY CUSTOMER.Name;

SELECT GENRE.Label, COUNT(StreamId) AS cnt
FROM GENRE JOIN MOVIE_GENRE USING(GenreId)
          LEFT OUTER JOIN STREAM USING(MovieId)
GROUP BY Label
HAVING cnt <1295;

SELECT MOVIE.Title, COUNT(StreamId) AS N, SUM(STREAM.Charge)
FROM MOVIE JOIN STREAM USING(MovieId)
          JOIN MOVIE_GENRE USING(MovieId)
          JOIN GENRE USING(GenreId)
WHERE Label = 'Action'
GROUP BY MOVIE.Title
ORDER BY N DESC, MOVIE.Title
LIMIT 20;


UPDATE STREAM SET Charge = Charge + 1.5
  WHERE STREAM.MovieId IN(
    SELECT MovieId FROM MOVIE
    JOIN MOVIE_ACTOR USING(MovieId)
    JOIN ACTOR USING(ActorId)
    WHERE ACTOR.Name = 'Denzel Washington'
  )
  AND STREAM.CustomerId IN(
    SELECT CustomerId FROM CUSTOMER
    JOIN COUNTRY ON(CUSTOMER.Country=COUNTRY.Name)
    JOIN REGION ON(COUNTRY.RegionId=REGION.RegionId)
    WHERE REGION.Name = 'Europe'
  );

SELECT MOVIE.Title FROM MOVIE
WHERE Duration >=140 AND MovieId NOT IN(
  SELECT MovieId FROM STREAM JOIN CUSTOMER USING(CustomerId)
  JOIN COUNTRY ON(CUSTOMER.Country=COUNTRY.Name)
  JOIN REGION ON(COUNTRY.RegionId=REGION.RegionId)
  WHERE REGION.Name = 'Asia'
)
ORDER BY MOVIE.Title;
