SELECT * FROM MOVIE WHERE Year >=2000
ORDER BY Duration DESC, Year DESC, Title
LIMIT 15;

SELECT MOVIE.Title,COUNT(StreamId) AS N FROM MOVIE JOIN STREAM USING(MovieId)
WHERE YEAR(StreamDate)=2017
GROUP BY MOVIE.Title
HAVING N>=10
ORDER BY N DESC, MOVIE.Title;

DELETE FROM STREAM WHERE STREAM.CustomerId IN(
  SELECT CustomerId FROM CUSTOMER
  WHERE CUSTOMER.Active = 0  AND CUSTOMER.Country = 'India'
);

SELECT MOVIE.Title, ACTOR.Name
FROM ACTOR JOIN MOVIE_ACTOR USING(ActorId) JOIN MOVIE USING(MovieId)
WHERE ACTOR.Name LIKE 'F%';

SELECT CUSTOMER.Name, COUNT(StreamId) AS N
FROM CUSTOMER LEFT OUTER JOIN STREAM ON(CUSTOMER.CustomerId=STREAM.CustomerId)
WHERE CUSTOMER.Country = 'India'
GROUP BY CUSTOMER.Name
HAVING N <5;

SELECT MOVIE.Title, COUNT(StreamId) AS N, MAX(STREAM.Charge)
FROM MOVIE JOIN MOVIE_ACTOR USING(MovieId) JOIN ACTOR USING(ActorId)
          JOIN STREAM USING(MovieId)
WHERE ACTOR.Name ='Brad Pitt'
GROUP BY MOVIE.Title
HAVING N>5
ORDER BY N DESC, MOVIE.Title;

UPDATE CUSTOMER SET CUSTOMER.Active=FALSE
WHERE CUSTOMER.CustomerId NOT IN(
  SELECT STREAM.CustomerId FROM STREAM
  WHERE StreamDate > '2018-09-01 00:00:00'
)
AND CUSTOMER.Country IN(
  SELECT COUNTRY.Name FROM COUNTRY JOIN REGION USING(RegionId)
  WHERE REGION.Name = 'Africa'
);

SELECT ACTOR.Name FROM ACTOR
WHERE ACTOR.ActorId NOT IN(
  SELECT MOVIE_ACTOR.ActorId FROM MOVIE_ACTOR JOIN MOVIE USING(MovieId)
              JOIN STREAM USING(MovieId) JOIN CUSTOMER USING(CustomerId)
              WHERE CUSTOMER.Country IN(
                SELECT COUNTRY.Name FROM COUNTRY JOIN REGION USING(RegionId)
                WHERE REGION.Name = 'Europe'
              )

)
GROUP BY ACTOR.Name
ORDER BY ACTOR.Name;
