SELECT * FROM MOVIE
WHERE Year>=2000
ORDER BY Duration DESC, Year DESC, Title
LIMIT 15;

SELECT Title, COUNT(StreamId) AS count
FROM MOVIE JOIN STREAM USING(MovieId)
WHERE YEAR(StreamDate) = 2017
GROUP BY Title
HAVING count >=10
ORDER BY count DESC, Title;

SELECT * FROM STREAM NATURAL JOIN CUSTOMER
WHERE Active = 0 AND Country = 'India';

DELETE FROM STREAM
WHERE STREAM.CustomerId IN(
  SELECT CUSTOMER.CustomerId FROM CUSTOMER
  WHERE Active = 0 AND Country = 'India'
);

/*     PERGUNTA D    */
SELECT MOVIE.Title, ACTOR.Name
FROM MOVIE
 JOIN MOVIE_ACTOR USING(MovieId)
 JOIN ACTOR USING(ActorId)
WHERE ACTOR.Name LIKE 'F%';

/*     PERGUNTA E    */

SELECT CUSTOMER.Name, COUNT(StreamId) AS C
FROM CUSTOMER LEFT OUTER JOIN STREAM USING(CustomerId)
WHERE CUSTOMER.Country = 'India'
GROUP BY CUSTOMER.Name
HAVING C <5;

/*     PERGUNTA F    */

SELECT MOVIE.Title,COUNT(StreamId) AS C, MAX(Charge)
FROM MOVIE
  JOIN STREAM USING(MovieId)
 JOIN MOVIE_ACTOR USING(MovieId)
 JOIN ACTOR USING(ActorId)
WHERE ACTOR.Name = 'Brad Pitt'
GROUP BY MOVIE.Title
HAVING C>=5
ORDER BY C DESC, Title;

/*     PERGUNTA G    */

UPDATE CUSTOMER SET Active = 0
WHERE Country IN (
  SELECT COUNTRY.Name FROM COUNTRY
  JOIN REGION USING(RegionId)
  WHERE REGION.Name = 'Africa'
)
AND CustomerId NOT IN (
  SELECT STREAM.CustomerId FROM STREAM
  WHERE YEAR(StreamDate) > 2019
  OR (YEAR(StreamDate) = 2018 AND MONTH(StreamDate)>=9)
);

/*     PERGUNTA H    */


SELECT ACTOR.Name FROM ACTOR
WHERE ACTOR.ActorId NOT IN(
  SELECT MOVIE_ACTOR.ActorId FROM MOVIE_ACTOR
  JOIN MOVIE USING(MovieId)
 WHERE MOVIE.MovieId IN(
   SELECT STREAM.MovieId FROM STREAM
     JOIN CUSTOMER USING(CustomerId)
     JOIN COUNTRY ON(CUSTOMER.Country=COUNTRY.Name)
     JOIN REGION USING(RegionId)
     WHERE REGION.Name = 'Europe'
 )
)
GROUP BY ACTOR.Name
ORDER BY ACTOR.Name;
