SELECT StreamDate, MOVIE.Title, CUSTOMER.Name, CUSTOMER.Country
FROM CUSTOMER JOIN STREAM USING(CustomerId) JOIN MOVIE USING(MovieId)
WHERE CUSTOMER.Country <> 'United States'
AND MOVIE.MovieId IN(
  SELECT MOVIE_ACTOR.MovieId FROM MOVIE_ACTOR JOIN ACTOR USING(ActorId)
  WHERE ACTOR.Name = 'Brad Pitt'
  AND MOVIE_ACTOR.MovieId  NOT IN(
    SELECT MOVIE_GENRE.MovieId FROM MOVIE_GENRE JOIN GENRE USING(GenreId)
    WHERE GENRE.Label = 'Action'
  )
)
ORDER BY StreamDate DESC
LIMIT 20;
