SELECT * FROM STREAM
WHERE Charge > 6
ORDER BY StreamDate Desc
LIMIT 20;


SELECT CUSTOMER.Country, COUNT(*) AS COUNT FROM CUSTOMER
WHERE ACTIVE = 1
GROUP BY CUSTOMER.Country
HAVING COUNT >=5
ORDER BY COUNT DESC, CUSTOMER.Country ASC;

DELETE FROM STREAM
WHERE STREAM.Charge <= 7.5
AND MovieId IN (
  SELECT MovieId FROM MOVIE
  WHERE MOVIE.Title LIKE '%Star Wars%'
);

SELECT CUSTOMER.Name, CUSTOMER.Country, CUSTOMER.City
FROM CUSTOMER JOIN COUNTRY ON(CUSTOMER.Country=COUNTRY.Name)
    JOIN REGION USING(RegionId)
WHERE REGION.Name = 'Africa';

SELECT Label, COUNT(StreamId) AS N
FROM GENRE JOIN MOVIE_GENRE USING(GenreId)
   LEFT OUTER JOIN STREAM USING(MovieId)
GROUP BY Label
HAVING N<1295;

SELECT MOVIE.Title, COUNT(StreamId) AS N, SUM(Charge)
  FROM MOVIE JOIN MOVIE_GENRE USING(MovieId)
  JOIN GENRE USING(GenreId)
  LEFT OUTER JOIN STREAM USING(MovieId)
  WHERE Label = 'Action'
  GROUP BY MOVIE.Title
  ORDER BY N DESC, Title
  LIMIT 20;

UPDATE STREAM SET Charge = Charge + 1.5
  WHERE MovieId IN (
    SELECT MovieId FROM MOVIE
    JOIN MOVIE_ACTOR USING(MovieId)
    JOIN ACTOR USING(ActorId)
    WHERE ACTOR.Name = 'Denzel Washington'
  ) AND CustomerId IN(
    SELECT CustomerId FROM CUSTOMER
    JOIN COUNTRY ON(CUSTOMER.Country = COUNTRY.Name)
    JOIN REGION USING(RegionId)
    WHERE REGION.Name = 'Europe'
  );

  /*NATURAL JOINS*
customer para a esquerda é tudo natural joins*/


SELECT M.Title FROM MOVIE M
WHERE M.Duration >=140 AND M.MovieId NOT IN (
  SELECT S.MovieId FROM STREAM S
  WHERE S.CustomerId IN(
    SELECT C.CustomerId FROM CUSTOMER C
    JOIN COUNTRY ON(C.Country = COUNTRY.Name)
    JOIN REGION USING(RegionId)
    WHERE REGION.Name = 'Asia'
  )
  )
ORDER BY M.Title;
