SELECT Duration, Year, Title FROM MOVIE
WHERE Duration<120 AND Year >2000
ORDER BY Duration DESC, Year, Title DESC
LIMIT 25;

SELECT GENRE.Label, COUNT(MOVIE_GENRE.MovieId) AS N, SUM(MOVIE.Duration)
FROM GENRE JOIN MOVIE_GENRE USING(GenreId) JOIN MOVIE USING(MovieId)
WHERE MOVIE.Year < 1980
GROUP BY GENRE.Label
HAVING N>=5
ORDER BY N DESC, GENRE.Label;

DELETE FROM MOVIE_ACTOR
WHERE MovieId IN(
  SELECT MovieId FROM MOVIE
  WHERE Year = 2015 AND Duration>120
);

SELECT COUNTRY.Name, REGION.Name, STAFF.Name
FROM COUNTRY JOIN REGION USING(RegionId)
            JOIN STAFF ON(REGION.RegionManager=STAFF.StaffId)
WHERE COUNTRY.Name LIKE 'C%'
GROUP BY COUNTRY.Name;

SELECT COUNTRY.Name, COUNT(StreamId) AS N
FROM COUNTRY JOIN CUSTOMER ON (COUNTRY.Name=CUSTOMER.Country)
        LEFT OUTER JOIN STREAM ON(CUSTOMER.CustomerId=STREAM.CustomerId)
WHERE CUSTOMER.Name LIKE '%d'
GROUP BY COUNTRY.Name
HAVING N<=23;

SELECT StreamDate, MOVIE.Title, CUSTOMER.Name, CUSTOMER.Country
FROM STREAM JOIN CUSTOMER USING(CustomerId) JOIN MOVIE USING(MovieId)
WHERE CUSTOMER.Country <> 'United States'
AND MOVIE.MovieId IN(
  SELECT MOVIE_ACTOR.MovieId FROM MOVIE_ACTOR JOIN ACTOR USING(ActorId)
  WHERE ACTOR.Name = 'Brad Pitt'
  AND MOVIE_ACTOR.MovieId  IN(
    SELECT MOVIE_GENRE.MovieId FROM MOVIE_GENRE JOIN GENRE USING(GenreId)
    WHERE Label <> 'Action'
  )
)
GROUP BY MOVIE.Title
ORDER BY StreamDate DESC
LIMIT 20;



UPDATE STREAM SET Charge = Charge + 1
WHERE STREAM.CustomerId IN (
  SELECT CUSTOMER.CustomerId FROM CUSTOMER
          JOIN COUNTRY ON(CUSTOMER.Country = COUNTRY.Name)
          JOIN REGION ON(COUNTRY.RegionId=REGION.RegionId)
  WHERE REGION.Name<>'Asia'
)
AND STREAM.MovieId IN(
  SELECT MOVIE.MovieId FROM MOVIE JOIN MOVIE_ACTOR USING(MovieId)
                                  JOIN ACTOR USING(ActorId)
  WHERE ACTOR.Name = 'Tom Cruise'
  AND MOVIE.Duration<145
);



SELECT COUNTRY.Name, GENRE.Label, COUNT(StreamId)
FROM COUNTRY JOIN REGION USING(RegionId)
            JOIN CUSTOMER ON(COUNTRY.Name=CUSTOMER.Country)
            JOIN STREAM USING(CustomerId)
            JOIN MOVIE USING(MovieID)
            JOIN MOVIE_GENRE USING(MovieID)
            JOIN GENRE USING(GenreId)
WHERE REGION.Name = 'Other Countries'
GROUP BY STREAM.StreamId
ORDER BY COUNTRY.Name, GENRE.Label;
